### ISSUE TITLE
Incredibly fragmented pages

### ISSUE THREAD

**Issue by MrShooter42** [Fusion-Lightguns/Fusion-Mini#1]
The pages are confusing and hard to navigate. They should be cleaned up. The Fusion Mini should link firmware, software, STLs, part lists, and assembly instructions.

**Comment by Fusion-Lightguns** [comment]
If that format makes it easier to understand, I will gladly update this github this evening.

**Comment by Fusion-Lightguns** [comment]
General layout & all info updated/currently updating. I feel issue has been resolved .
